name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ваши шаги по сборке и тестам

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi20:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi20:latest

      # Для Render: достаточно push'а, платформа сама подхватит обновление

      # Для Heroku (если деплой через контейнер)
      - name: Install Heroku CLI
        uses: akshnz/heroku-cli-gh-actions@v1.3.2

      - name: Login to Heroku Container Registry
        run: heroku container:login

      - name: Push to Heroku Container Registry
        run: |
          heroku container:push web --app ${{ secrets.HEROKU_APP_NAME }}
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
